# Generated by Django 4.2.3 on 2023-08-01 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_room_options_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
