# Generated by Django 4.2.3 on 2023-08-03 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
    ]
